### ISSUE TITLE
Cannot pass multiple inputs to a recurrent policy with PPO

### ISSUE THREAD

**Issue by tarokiritani** [pfnet/pfrl#128]
Here is the definition of my policy that recurrently maps two inputs to an action and value estimation. The policy takes two `PackedSequence`s put in a tuple. The model works (more or less) as I expected.
```
class Foo(nn.Module):
  def __init__(self):
    super().__init__()
    self.cnn = nn.Sequential(nn.Conv2d(3, 32, 3),
                  nn.ReLU(),
                  nn.Conv2d(32, 64, 3),
                  nn.ReLU(),
                  nn.Flatten())
 
  def forward(self, x):
    cnn_out = self.cnn(x[0])
    out = torch.cat((cnn_out, x[1]), 1)
    return out
 
foo = pfrl.nn.RecurrentSequential(
    Foo(),
    nn.GRU(num_layers=1, input_size=64 * 4 * 4 + 12, hidden_size=128),
    pfrl.nn.Branched(
        nn.Sequential(nn.Linear(128, 4),
                      SoftmaxCategoricalHead(),),
        nn.Linear(128, 1),
    )
)
 
print(foo((torch.nn.utils.rnn.pack_sequence(torch.rand(1, 32, 3, 8, 8)), torch.nn.utils.rnn.pack_sequence(torch.rand(1, 32, 12))), None))
```

I am trying to use this with PPO. This time I put two tensors in a tuple hoping that they are converted to two `PackedSequence`s in the agent. However, the preprocessing of the tensors throws the following error:

```
opt = torch.optim.Adam(foo.parameters(), lr=2.5e-4, eps=1e-5)

def phi(x):
    return x
 
agent = PPO(
        foo,
        opt,
        gpu=-1,
        phi=phi,
        update_interval=8,
        minibatch_size=32*8,
        epochs=4,
        clip_eps=0.1,
        clip_eps_vf=None,
        standardize_advantages=True,
        entropy_coef=1e-2,
        recurrent=True,
        max_grad_norm=0.5,
    )

agent.batch_act(
    (
        (torch.rand([1, 32, 3, 8, 8]), torch.rand([1, 32, 12]),)
     ,),
)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-70b107928cd6> in <module>()
      1 agent.batch_act(
      2     (
----> 3         (torch.rand([1, 32, 3, 8, 8]), torch.rand([1, 32, 12]),)
      4      ,),
      5 )

3 frames
/usr/local/lib/python3.6/dist-packages/pfrl/agents/ppo.py in batch_act(self, batch_obs)
    652     def batch_act(self, batch_obs):
    653         if self.training:
--> 654             return self._batch_act_train(batch_obs)
    655         else:
    656             return self._batch_act_eval(batch_obs)

/usr/local/lib/python3.6/dist-packages/pfrl/agents/ppo.py in _batch_act_train(self, batch_obs)
    706                     self.train_recurrent_states,
    707                 ) = one_step_forward(
--> 708                     self.model, b_state, self.train_prev_recurrent_states
    709                 )
    710             else:

/usr/local/lib/python3.6/dist-packages/pfrl/utils/recurrent.py in one_step_forward(rnn, batch_input, recurrent_state)
    139         object: New batched recurrent state.
    140     """
--> 141     pack = pack_one_step_batch_as_sequences(batch_input)
    142     y, recurrent_state = rnn(pack, recurrent_state)
    143     return unpack_sequences_as_one_step_batch(y), recurrent_state

/usr/local/lib/python3.6/dist-packages/pfrl/utils/recurrent.py in pack_one_step_batch_as_sequences(xs)
    115         return tuple(pack_one_step_batch_as_sequences(x) for x in xs)
    116     else:
--> 117         return nn.utils.rnn.pack_sequence(xs[:, None])
    118 
    119 

TypeError: list indices must be integers or slices, not tuple
```

The input tuple is converted to a list by `pfrl.util.batch_states()`, which is called inside `pfrl.agents.PPO._batch_act_train()`. The list is then passed to `pfrl.util.recurrent.pack_one_step_batch_as_sequences()` , but it expects a tuple. Maybe we can just collect multiple inputs in a tuple instead of a list in pfrl.util.batch_states()?

I am still figuring out pfrl, and perhaps I am not correctly passing multiple inputs to a recurrent policy. Suggestions are welcome.

The snippet is found here: https://colab.research.google.com/drive/1wqEtZTvwu0IN7oZnbrp34W7lBxVyGhp6?usp=sharing

**Comment by tkelestemur** [comment]
I had the exact same problem and couldn't find a way to use tuples as the observation from the agent. My observation space has a two-channel image and vector with length 320. I ended up creating a three-channel image, convert vector data to 2D matrix and assign it to the 3rd channel of the image. In the forward pass of the network, I unpack the 3rd image and reshape it to vector. 

Below is the policy:

```
class IMPALAGRU(nn.Module):
    def __init__(self, obs_dim=3):
        super(IMPALAGRU, self).__init__()

        self.image_encoder = IMPALACNN(obs_dim=obs_dim - 1)

    def forward(self, obs):
        images = obs[:, 0:2]
        tactile = obs[:, 2]
        tactile = tactile.view(-1, 64 * 64)
        tactile = tactile[:, 0:320]

        image_features = self.image_encoder(images)
        features = torch.cat((image_features, tactile), dim=1)

        return features 

model = pfrl.nn.RecurrentSequential(
    IMPALAGRU(),
    lecun_init(nn.GRU(num_layers=1, input_size=512 + 320, hidden_size=512)),
    pfrl.nn.Branched(
        nn.Sequential(
            lecun_init(nn.Linear(512, num_actions), 1e-2),
            SoftmaxCategoricalHead(),
        ),
        lecun_init(nn.Linear(512, 1))
    )
)

**Comment by tarokiritani** [comment]
@tkelestemur Thanks for sharing your experience and workaround! Your approach may be the way to go for now.

**Comment by muupan** [comment]
Thanks for reporting the issue! I think this needs a fix.

If I understand correctly, what is going on is:
- PyTorch's `default_collate`, which is called inside PFRL's `batch_states`, turns any Sequence into list. https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py#L76-L83
- PFRL's `pack_one_step_batch_as_sequences` expects only `tuple` or `torch.Tensor`, not list. https://github.com/pfnet/pfrl/blob/master/pfrl/utils/recurrent.py#L121-L125

Since we cannot modify `default_collate`, the easiest solution would be let `pack_one_step_batch_as_sequences` accept `list`. Can anyone check if this workaround works?

**Comment by tarokiritani** [comment]
Let me check this tomorrow or the day after.

**Comment by tarokiritani** [comment]
I should have mentioned this, but in my script above, I passed a tuple of a tuple of two tensors. This is of course strange. If a tuple of tensors is used, the collate function tries to concatenate the tensors.

```
action = agent.batch_act(
     (torch.rand([32, 3, 8, 8]), torch.rand([32, 12])),
)


File "/Users/taro.kiritani/miniconda3/envs/pfrl_test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
RuntimeError: stack expects each tensor to be equal size, but got [32, 3, 8, 8] at entry 0 and [32, 12] at entry 1
```

Trying to circumvent this error, I used a nested tuple and faced the issue regarding tuple vs. list.

**Comment by muupan** [comment]
Let's say an observation is shaped as a tuple of two arrays, whose shapes are (3,8,8) and (12,), respectively.`Agent.batch_act` expects a sequence of observations like below:
```python
# take 3 observations and return 3 actions
actions = agent.batch_act([
    (np.zeros((3, 8, 8), dtype="f"), np.zeros((12,), dtype="f")),
    (np.zeros((3, 8, 8), dtype="f"), np.zeros((12,), dtype="f")),
    (np.zeros((3, 8, 8), dtype="f"), np.zeros((12,), dtype="f")),
])
```

It cannot accept already collated input like `(torch.rand([32, 3, 8, 8]), torch.rand([32, 12]))`.

**Comment by tarokiritani** [comment]
In my case, another pytorch network outputs collated tensors. I might need to split and collate again. That might not be too bad..

**Comment by muupan** [comment]
Unfortunately, PFRL's agents currently do not support already batched input, whether or not the policy is recurrent. I understand letting agents to accept batched input is better in your case.

**Comment by tarokiritani** [comment]
I tried the following:

```
input_0 = torch.rand([32, 3, 8, 8])
input_1 = torch.rand([32, 12])
collated_input = []
for i_0, i_1 in zip(torch.split(input_0, 1, dim=0), torch.split(input_1, 1, dim=0)):
    collated_input.append((i_0.squeeze(0), i_1.squeeze(0)))

action = agent.batch_act(
        collated_input
        )
```

This throws the original error.
```
 File "/Users/taro.kiritani/Documents/repos/pfrl/pfrl/utils/recurrent.py", line 124, in pack_one_step_batch_as_sequences
    if isinstance(xs, tuple):
TypeError: list indices must be integers or slices, not tuple
```

What happened to the input was the following:

1. Tuple to list conversion in `batch_states`(https://github.com/pfnet/pfrl/blob/056cb30ab85e78728ed7dac706feb77ce1dbabf4/pfrl/utils/batch_states.py#L31
2. `default_collate` collates the input and return a list of two collated tensors. https://github.com/pytorch/pytorch/blob/f1f9b049d83fc20256a244d62b2eca6548a02fd5/torch/utils/data/_utils/collate.py#L83
3. Tensors in the list are sent to a device. This function actually can handle both tuple and list types: https://github.com/pfnet/pfrl/blob/056cb30ab85e78728ed7dac706feb77ce1dbabf4/pfrl/utils/batch_states.py#L7
4. `pack_one_step_batch_as_sequences` complains because it expects a tuple not a list. https://github.com/pfnet/pfrl/blob/284ed1f43b32654a2ec1569b16a0f6b9acbd5e79/pfrl/utils/recurrent.py#L122

I changed `if isinstance(xs, tuple):` to `if isinstance(xs, tuple) or isinstance(xs, list):` in `pack_one_step_batch_as_sequences`, and the error is gone. I am not sure yet if this is the way to go. Apparently similar type checking is done in many places in recurrent.py. Maybe these need to be changed as well?

https://github.com/pfnet/pfrl/blob/284ed1f43b32654a2ec1569b16a0f6b9acbd5e79/pfrl/utils/recurrent.py#L131
https://github.com/pfnet/pfrl/blob/284ed1f43b32654a2ec1569b16a0f6b9acbd5e79/pfrl/utils/recurrent.py#L74

**Comment by tarokiritani** [comment]
Wrapping `default_collate` in `batch_states` might be a better approach.
Something like this:
```
return _to_recursive(default_collate(features), device)
```
to
```
collated_features = default_collate(features)
if isinstance(collated_features, list):
    collated_features = tuple(collated_features)
return _to_recursive(collated_features, device)
```

**Comment by muupan** [comment]
> I changed if isinstance(xs, tuple): to if isinstance(xs, tuple) or isinstance(xs, list): in pack_one_step_batch_as_sequences, and the error is gone. I am not sure yet if this is the way to go. Apparently similar type checking is done in many places in recurrent.py. Maybe these need to be changed as well?

Thank you for confirming it works! There might be other changes required, but I'm not sure. Also, I forgot the fact that `default_collate` is recursively defined, which makes it difficult to wrap it. I now think that modifying `pack_one_step_batch_as_sequences` is better.

**Comment by tarokiritani** [comment]
I wrapped the output of `default_collate` in `batch_states`, and it works too for a tuple of tuples of tensors.

We do not expect more deeply nested tuples, do we? Since gym also uses tuples to put together different kinds of inputs, we maybe had better stick to tuples?

**Comment by muupan** [comment]
I guess that would not work for a case like this.
```
actions = agent.batch_act([
    (np.zeros((3, 8, 8), dtype="f"), (np.zeros((12,), dtype="f"), np.zeros((7,), dtype="f"))),
    (np.zeros((3, 8, 8), dtype="f"), (np.zeros((12,), dtype="f"), np.zeros((7,), dtype="f"))),
    (np.zeros((3, 8, 8), dtype="f"), (np.zeros((12,), dtype="f"), np.zeros((7,), dtype="f"))),
])
```

But I admit this is a rare case. I think your solution of checking the output of `default_collate` is fine. Would you be willing to make a pull request?

**Comment by tarokiritani** [comment]
Sure, I will also add some tests to https://github.com/pfnet/pfrl/blob/master/tests/utils_tests/test_batch_states.py .

**Comment by tarokiritani** [comment]
Turned out type checking was already done in the test. This passes after the change in batch_states.py. https://github.com/tarokiritani/pfrl/blob/284ed1f43b32654a2ec1569b16a0f6b9acbd5e79/tests/utils_tests/test_batch_states.py#L28

**Comment by muupan** [comment]
Resolved by #129

**Comment by Aakriti05** [comment]
Hi,

I am a doing similar thing of importing tuple from gym environment for my observations. The observation space is the following tuple (First is a 1d vector and second is a single channel image)- 

`
self.observation_space = spaces.Tuple((spaces.Box(low=0, high=2, shape=(1200, 1), dtype=np.uint8), spaces.Box(low=0, high=1, shape=(64, 64), dtype=np.uint8)))`

The training code is -
```

model = pfrl.nn.RecurrentSequential(
        Network_policy(),
        nn.GRU(num_layers=1, input_size=256, hidden_size=128),
        pfrl.nn.Branched(nn.Sequential(nn.Linear(128, 100), SoftmaxCategoricalHead()), nn.Linear(128, 1))
    )

opt = torch.optim.Adam(model.parameters(), lr=3e-4, eps=1e-5)

    agent = PPO(
        model,
        opt,
        # obs_normalizer=obs_normalizer,
        gpu=args.gpu,
        update_interval=args.update_interval,
        minibatch_size=args.batch_size,
        epochs=args.epochs,
        clip_eps_vf=None,
        entropy_coef=0,
        standardize_advantages=True,
        gamma=0.99,
        lambd=0.97,
    )

experiments.train_agent_batch_with_evaluation(
            agent=agent,
            env=make_batch_env(False),
            eval_env=make_batch_env(True),
            outdir=args.outdir,
            steps=args.steps,
            eval_n_steps=None,
            eval_n_episodes=args.eval_n_runs,
            eval_interval=args.eval_interval,
            log_interval=args.log_interval,
            max_episode_len=timestep_limit,
            save_best_so_far_agent=False,
        )

```

**I am getting the following error.** 

```

 File "/scratch/anaconda3/envs/pyt/lib/python3.8/site-packages/pfrl/wrappers/cast_observation.py", line 22, in observation
    return observation.astype(self.dtype, copy=False)
AttributeError: 'tuple' object has no attribute 'astype'
```



The network policy used above is defined as follows. Here obs is the tuple which is spitting. I have also tried using a list instead of tuple the same error exists for lists as well. - 

```
class Network_policy(nn.Module):
    def __init__(self):
        super(Network_policy, self).__init__()
        self.conv1 = nn.Conv2d(1, 8, 3, stride=4)
        self.conv2 = nn.Conv2d(8, 16, 3, stride=4)
        self.conv3 = nn.Conv2d(16, 32, 3, stride=4)

        self.linear1 = nn.Linear(1200, 64)
        self.linear2 = nn.Linear(64, 128)

    def forward(self, obs):
        image  =  nn.ReLU()(self.conv1(obs[1]))
        image =  nn.ReLU()(self.conv2(image))
        image =  nn.ReLU()(self.conv3(image))
        
        vector = nn.ReLU()(self.linear1(obs[0]))
        vector = nn.ReLU()(self.linear2(vector))

        out = nn.cat((image, vector),1)        
        return out
```
What can I do solve this error? Is the turnaround method mentioned [above] (https://github.com/pfnet/pfrl/issues/128#issuecomment-771248558) the only available option?

Thanks

**Comment by muupan** [comment]
@Aakriti05 As the error message suggests, the `CastObservation` wrapper does not support tuple observations. I guess you can resolve the error by removing the wrapper from your env and setting PPO's `phi` properly so that it can handle `uint8` observations.
