### ISSUE TITLE
Version of omegaconf and hydra

### ISSUE THREAD

**Issue by im-Kitsch** [pfnet/pfrl#165]
Hi,

looks Hydra and Omegaconf have changed the APIs and I cannot directly use your package from newest version, could you specify the version?

Best,

**Comment by muupan** [comment]
Hi, thanks for reporting the issue. pfrl does not directly depend hydra and omegaconf. Can you elaborate the issue?

**Comment by im-Kitsch** [comment]
hi,

Sorry, yes, I figured it out. Sorry for my mistake.

Best regards.
