### ISSUE TITLE
"from gym.wrappers import Monitor" has been deprecated

### ISSUE THREAD

**Issue by ThePeshMod** [pfnet/pfrl#172]
The Monitor from gym.wrappers has been deprecated. At the moment, you can;t even "import pflr", as immediately you are greeted with this:

ImportError: cannot import name 'Monitor' from 'gym.wrappers'

**Comment by ThePeshMod** [comment]
OK, it looks like it was deprecated in version gym 0.23.0 (along with gym.wrappers.monitoring.stats_recorder), so if you want to use PFRL, you should install gym 0.22.0, at least until this library is updated.

**Comment by muupan** [comment]
Thanks for raising the issue. pfrl==0.4.0 has been released, which should solve it.
