### ISSUE TITLE
Recurrent DDPG implemented? 

### ISSUE THREAD

**Issue by satpreetsingh** [pfnet/pfrl#38]
Per the code for DDPG, it does not seem like recurrent networks are implemented yet but seem to be supported: 

`https://github.com/pfnet/pfrl/blob/master/pfrl/agents/ddpg.py`
  
Can you provide some information about what algorithm/paper you are referring to? 
Is it: Memory-based control with recurrent neural networks
https://arxiv.org/abs/1512.04455 

When this could be expected to be implemented? Thanks!

**Comment by muupan** [comment]
> Is it: Memory-based control with recurrent neural networks https://arxiv.org/abs/1512.04455

Yes.

> When this could be expected to be implemented? Thanks!

It is not decided. One reason why it is not easy is: https://github.com/pytorch/pytorch/issues/31423
