### ISSUE TITLE
Saving training statistics

### ISSUE THREAD

**Issue by tkelestemur** [pfnet/pfrl#48]
Hello all,

I'm training a custom environment that follow gym API. I've been using PPO and it seems it's able to learn successfully. However, I couldn't figure out how to save the statistics such as `average_R`. If I wrap the environment with Monitor class, I can get the statistics of indivudial environments but I also would like to save the training statistics. Note that I don't use evaluations during training. My training scrips is below:

```
def train(args):
    pfrl.utils.set_random_seed(args.seed)
    env = create_multi_env(seed=args.seed, num_envs=args.num_envs)

    model = create_model()
    opt = torch.optim.Adam(model.parameters(), lr=2.5e-4, eps=1e-5)
    agent = create_agent(model, opt)

    experiments.train_agent_batch(
        agent=agent,
        env=env,
        outdir=args.outdir,
        steps=args.steps,
        checkpoint_freq=int(1000),
        log_interval=int(1000)
    )

    agent.save('agents')
```

PS. Thanks for the great library!

**Comment by muupan** [comment]
Unfortunately, `average_R` is printed but not saved to a file right now. I almost always use evaluations, and training statistics are saved only when evaluation happens. I agree it would be good if there is some option to save training stats including `average_R` regularly (perhaps after every N timesteps) during training. PR is welcome.

**Comment by tkelestemur** [comment]
Thanks for the answer @muupan. For my case, I run the experiments after training is done. I'll try to submit a PR for getting statistics during training.
