### ISSUE TITLE
Support for Multiple GPUs

### ISSUE THREAD

**Issue by peasant98** [pfnet/pfrl#78]
Hi,

First, thanks for the work on this repo - it's great.

Second, what is the priority level of getting models to work on multiple GPUs? I was curious since my university's supercomputer cluster allows for using multiple GPUs, which would definitely speed up training.

Thanks!

**Comment by belldandyxtq** [comment]
Hi,

Thank you for the question.

I think if you just want to use multiple GPUs to do data parallelism, it is fairly easy with [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#torch.nn.parallel.DistributedDataParallel). 
The only things you to do are 
1. passing your model to the `DistributedDataParallel`
2. launching the job with the `python -m torch.distributed.launch`

You may want to use the backend `nccl` if you are using GPUs to get better performance

For more details: 
https://pytorch.org/docs/stable/notes/ddp.html
https://pytorch.org/tutorials/intermediate/ddp_tutorial.html
https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py
